# schema.yml for marts models
# Covers dim_patients and fct_appointments

version: 2

models:

  # -----------------------------------------------------------------------
  - name: dim_patients
    columns:

      - name: patient_sk
        tests:
          - not_null
          - unique          

      - name: patient_id
        tests:
          - not_null
          - unique

      - name: patient_name
        tests:
          - not_null

      - name: plan_tier
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: 
                  - 'BRONZE'
                  - 'SILVER'
                  - 'GOLD'
                  - 'NONE'

      - name: total_appointments
        tests:
          - not_null

      - name: total_spend
        tests:
          - not_null

  # -----------------------------------------------------------------------
  - name: fct_appointments
    columns:

      - name: appointment_sk
        tests:
          - not_null
          - unique

      - name: appointment_id
        tests:
          - not_null
          - unique

      - name: patient_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_sk

      - name: patient_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_id

      - name: status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                 - 'SCHEDULED'
                 - 'COMPLETED'
                 - 'CANCELLED'

      - name: total_paid
        tests:
          - not_null
