# schema.yml for staging models
# Generic tests are defined here. dbt auto-generates the SQL and runs them.

version: 2

models:

  # -----------------------------------------------------------------------
  - name: stg_patients
    columns:

      - name: patient_id
        tests:
          - not_null       
          - unique          
      - name: email
        tests:
          - not_null
          - unique          

      - name: first_name
        tests:
          - not_null

      - name: gender
        tests:
          - accepted_values:
              arguments:            
                values: 
                  - 'Male'
                  - 'Female'
                  - 'Unknown' 

      - name: date_of_birth
        tests:
          - not_null       
  # -----------------------------------------------------------------------
  - name: stg_doctors

    columns:

      - name: doctor_id
        tests:
          - not_null
          - unique

      - name: doctor_name
        tests:
          - not_null

      - name: consultation_fee
        tests:
          - not_null

      - name: is_available
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: 
                  - true
                  - false

      - name: fee_band
        tests:
          - accepted_values:
              arguments:
                values: 
                  - 'Low'
                  - 'Medium'
                  - 'High'
                  - 'Invalid'

  # -----------------------------------------------------------------------
  - name: stg_appointments
    columns:

      - name: appointment_id
        tests:
          - not_null
          - unique

      - name: patient_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_patients')
              field: patient_id

      - name: doctor_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_doctors')
              field: doctor_id

      - name: status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: 
                  - 'SCHEDULED'
                  - 'COMPLETED'
                  - 'CANCELLED' 

      - name: appointment_date
        tests:
          - not_null

      - name: fee_charged
        tests:
          - not_null
