version: 2
sources:
  - name: raw
    database: ASSIGNMENT2
    schema: RAW
    tables:
      - name: APPOINTMENTS
      - name: CLINICS
      - name: DOCTORS
      - name: INSURANCE_PLANS
      - name: PATIENTS
      - name: PAYMENTS

  - name: Stage
    database: ASSIGNMENT2
    schema: STAGING
    tables:
      - name: stg_appointments
      - name: stg_doctors
      - name: stg_patients
      - name: stg_payments
